### PR TITLE
PR: Issue template create for Invitation to the GitHub Community Organization

### PR DESCRIPTION
**Pull request by creative2113**
I have updated invitation issue.
please check and merge.

### CODE REVIEW

**Review by stanislavboik — APPROVED** [review]
Great job

**Review by goldsunshines — APPROVED** [review]
Yeah, it's Ok

**Review by silvershiny — APPROVED** [review]
That was that I wanted

**Review by noahstoner — APPROVED** [review]
Awesome.
Let's test after merge

**Review by popstar7 — APPROVED** [review]
Very nice

**Pull request merged**
